name: Build on Arduino IDE

on: [push]

jobs:
  build-arduino-ide:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Arduino cli
        run: |
          mkdir -p ~/local/bin
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=~/local/bin sh

      - name: Install platform
        run: ~/local/bin/arduino-cli core install arduino:avr

      - name: Install deps
        run: ~/local/bin/arduino-cli lib install EncButton GyverIO CRC32

      - name: Run build
        run: ~/local/bin/arduino-cli compile -v -b arduino:avr:nano DarkroomTimer/

      - name: Run build with custom UserConfig.h
        run: |
          for file in test/custom_configs/good/*; do
            echo "Check $file"
            cp "$file" DarkroomTimer/UserConfig.h
            ~/local/bin/arduino-cli compile -b arduino:avr:nano DarkroomTimer/
          done

      - name: Run build with bad custom UserConfig.h
        run: |
          for file in test/custom_configs/bad/*; do
            echo "Check $file"
            cp "$file" DarkroomTimer/UserConfig.h
            ~/local/bin/arduino-cli compile --warnings default -b arduino:avr:nano DarkroomTimer/ && false
          done
          true
